# Generated by Django 2.2.1 on 2019-06-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0002_auto_20190628_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='rz1',
            field=models.FloatField(blank=True, null=True, verbose_name='Root Zone 1'),
        ),
        migrations.AddField(
            model_name='reading',
            name='rz2',
            field=models.FloatField(blank=True, null=True, verbose_name='Root Zone 2'),
        ),
        migrations.AddField(
            model_name='reading',
            name='rz3',
            field=models.FloatField(blank=True, null=True, verbose_name='Root Zone 3'),
        ),
    ]
