# Generated by Django 2.2.1 on 2020-03-10 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0002_create_custom_season_view'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reading',
            unique_together={('date', 'site')},
        ),
    ]
