# Generated by Django 2.2.1 on 2019-06-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0003_auto_20190628_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='deficit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='effective_irrigation',
            field=models.FloatField(blank=True, help_text='keydata 9', null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='effective_rain_1',
            field=models.FloatField(blank=True, help_text='keydata 5', null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='effective_rainfall',
            field=models.FloatField(blank=True, help_text='keydata 6', null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='efflrr1',
            field=models.FloatField(blank=True, help_text='keydata 7', null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='efflrr2',
            field=models.FloatField(blank=True, help_text='keydata 8', null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='irrigation_litres',
            field=models.FloatField(blank=True, help_text='keydata 3', null=True, verbose_name='Irrigation in Litres'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='irrigation_mms',
            field=models.FloatField(blank=True, help_text='keydata 4', null=True, verbose_name='Irrigation in Millilitres'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='meter',
            field=models.FloatField(blank=True, help_text='keydata 2', null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='rain',
            field=models.FloatField(blank=True, help_text='keydata 1', null=True),
        ),
    ]
