# Generated by Django 2.2.1 on 2020-03-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0003_auto_20200311_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='rec_Fri',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='rec_Mon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='rec_Sat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='rec_Sun',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='rec_Thu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='rec_Tue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reading',
            name='rec_Wed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
