# Generated by Django 2.2.3 on 2019-08-09 01:47

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skeleton', '0004_kcreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probe',
            name='serial_number',
            field=models.CharField(default='Manual', max_length=100),
        ),
        migrations.AlterField(
            model_name='reading',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='serial_number',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='skeleton.Probe'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='skeleton.ReadingType'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('created_by', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
