# Generated by Django 2.2.1 on 2019-06-28 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0005_auto_20190628_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibration',
            name='serial_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skeleton.Probe'),
        ),
    ]
