# Generated by Django 2.2.3 on 2019-08-21 22:53

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skeleton', '0005_auto_20190809_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diviner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diviner_number', models.CharField(max_length=50)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('created_by', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skeleton.Site')),
            ],
        ),
        migrations.AlterField(
            model_name='reading',
            name='serial_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skeleton.Probe'),
        ),
        migrations.CreateModel(
            name='ProbeDiviner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('created_by', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('diviner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='skeleton.Diviner')),
                ('probe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skeleton.Probe')),
            ],
        ),
    ]
