# Generated by Django 2.2.3 on 2019-08-23 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skeleton', '0006_auto_20190822_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='attn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attn_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farm',
            name='owner',
            field=models.CharField(default='TEST', max_length=100),
        ),
    ]
