# Generated by Django 2.2.3 on 2020-03-19 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0006_auto_20200319_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='lower_strategy',
        ),
        migrations.RemoveField(
            model_name='site',
            name='upper_strategy',
        ),
        migrations.AddField(
            model_name='site',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skeleton.StrategyType'),
        ),
    ]
