# Generated by Django 2.2.1 on 2019-09-03 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0007_auto_20190823_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='attn',
        ),
    ]
