# Generated by Django 2.2.3 on 2020-03-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0007_auto_20200320_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategytype',
            name='percentage',
            field=models.IntegerField(blank=True, help_text='The difference that the lower strategy should be below the upper strategy for a site. This is taken from the high limit.', null=True),
        ),
    ]
