# Generated by Django 2.2.1 on 2019-09-09 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0008_remove_farm_attn'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reading',
            unique_together={('date', 'site')},
        ),
    ]
