# Generated by Django 2.2.3 on 2020-03-20 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0008_strategytype_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='wetted_width',
        ),
        migrations.AlterField(
            model_name='site',
            name='emitter_spacing',
            field=models.IntegerField(blank=True, null=True, verbose_name='Emitter Spacing (Meters)'),
        ),
        migrations.AlterField(
            model_name='site',
            name='plant_spacing',
            field=models.IntegerField(blank=True, null=True, verbose_name='Plant Spacing (Meters)'),
        ),
        migrations.AlterField(
            model_name='site',
            name='row_spacing',
            field=models.IntegerField(blank=True, null=True, verbose_name='Row Spacing (Meters)'),
        ),
    ]
