# Generated by Django 2.2.3 on 2019-09-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0010_site_site_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
