# Generated by Django 2.2.3 on 2020-03-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0010_auto_20200320_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='rec_Fri',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='rec_Mon',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='rec_Sat',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='rec_Sun',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='rec_Thu',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='rec_Tue',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='rec_Wed',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
