# Generated by Django 2.2.3 on 2019-09-18 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skeleton', '0011_auto_20190912_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='technician',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='technician_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
