# Generated by Django 2.2.3 on 2019-11-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0012_site_technician'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
