# Generated by Django 2.2.1 on 2020-03-29 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0012_auto_20200330_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='crop',
        ),
        migrations.AddField(
            model_name='site',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skeleton.Product'),
        ),
    ]
