# Generated by Django 2.2.1 on 2020-04-02 20:53

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skeleton', '0013_auto_20200330_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarietySeasonTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_date', models.DateField(default=django.utils.timezone.now, help_text='The day and month to create new season Critical Dates for all sites that are of this variety.')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('created_by', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('critical_date_type', models.ForeignKey(help_text='The Critical Date Type to create new season Critical Dates for all sites that are of this variety.', on_delete=django.db.models.deletion.CASCADE, to='skeleton.CriticalDateType')),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skeleton.Variety')),
            ],
        ),
    ]
