# Generated by Django 2.2.1 on 2019-11-14 03:32

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('skeleton', '0013_site_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFullName',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='reading',
            name='depth11',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='depth12',
        ),
        migrations.RemoveField(
            model_name='site',
            name='depth11',
        ),
        migrations.RemoveField(
            model_name='site',
            name='depth12',
        ),
        migrations.RemoveField(
            model_name='site',
            name='depth_he11',
        ),
        migrations.RemoveField(
            model_name='site',
            name='depth_he12',
        ),
    ]
