# Generated by Django 2.2.1 on 2019-11-17 20:53

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skeleton', '0014_auto_20191114_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDescription',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('skeleton.site',),
        ),
        migrations.RemoveField(
            model_name='season',
            name='period_from',
        ),
        migrations.RemoveField(
            model_name='season',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='season',
            name='period_to',
        ),
        migrations.RemoveField(
            model_name='site',
            name='bud_break',
        ),
        migrations.RemoveField(
            model_name='site',
            name='cd2',
        ),
        migrations.RemoveField(
            model_name='site',
            name='cd3',
        ),
        migrations.RemoveField(
            model_name='site',
            name='cd4',
        ),
        migrations.RemoveField(
            model_name='site',
            name='cd5',
        ),
        migrations.RemoveField(
            model_name='site',
            name='cd6',
        ),
        migrations.RemoveField(
            model_name='site',
            name='season_end',
        ),
        migrations.RemoveField(
            model_name='site',
            name='season_start',
        ),
        migrations.CreateModel(
            name='CriticalDateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('season_flag', models.BooleanField()),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('created_by', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CriticalDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('created_by', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='skeleton.Season')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='skeleton.Site')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_date_types', to='skeleton.CriticalDateType')),
            ],
        ),
    ]
