# Generated by Django 2.2.1 on 2019-11-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0015_auto_20191118_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='current_flag',
            field=models.BooleanField(default=None, help_text='Is this the current season, only one season can be the current season', null=True),
        ),
    ]
