# Generated by Django 2.2.1 on 2020-04-23 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0015_season_season_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(default='Crop', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skeleton.Crop'),
        ),
        migrations.AlterField(
            model_name='product',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skeleton.Variety'),
        ),
    ]
