# Generated by Django 2.2.1 on 2020-05-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0016_auto_20200424_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='emitter_rate',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='site',
            name='emitter_spacing',
            field=models.FloatField(default=1, verbose_name='Emitter Spacing (Meters)'),
        ),
        migrations.AlterField(
            model_name='site',
            name='plant_spacing',
            field=models.FloatField(default=1, verbose_name='Plant Spacing (Meters)'),
        ),
        migrations.AlterField(
            model_name='site',
            name='row_spacing',
            field=models.FloatField(default=1, verbose_name='Row Spacing (Meters)'),
        ),
    ]
