# Generated by Django 2.2.1 on 2020-05-08 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0017_auto_20200506_1438'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reading',
            unique_together={('date', 'site', 'type')},
        ),
    ]
