# Generated by Django 2.2.1 on 2019-11-18 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0017_create_custom_season_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonStartEnd',
            fields=[
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='skeleton.Season')),
                ('season_name', models.CharField(max_length=20)),
                ('site_name', models.CharField(max_length=100)),
                ('period_from', models.DateTimeField()),
                ('period_to', models.DateTimeField()),
            ],
            options={
                'db_table': 'skeleton_season_start_end',
                'managed': False,
            },
        ),
    ]
