# Generated by Django 2.2.1 on 2019-11-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0018_seasonstartend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='created_date',
        ),
    ]
