# Generated by Django 3.0.6 on 2020-06-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0019_auto_20200512_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reading',
            options={'get_latest_by': 'date'},
        ),
    ]
