# Generated by Django 2.2.1 on 2019-12-01 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0019_auto_20191119_0753'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reading',
            unique_together={('date', 'site', 'type')},
        ),
    ]
