# Generated by Django 2.2.1 on 2019-12-02 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0020_auto_20191202_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skeleton.ReadingType'),
        ),
    ]
