# Generated by Django 2.2.1 on 2019-12-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0021_auto_20191203_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='deficit',
            field=models.FloatField(blank=True, help_text='Deficit is the difference between the full point reading and root zone 1', null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='estimated_dwu',
            field=models.FloatField(blank=True, help_text='EDWU is KC Reading for crop multiplied by ET reading for region', null=True, verbose_name='Estimated Daily Water Use'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='irrigation_litres',
            field=models.FloatField(blank=True, help_text='Difference in Meter readings multipled by the Irrigation Postion', null=True, verbose_name='Irrigation in Litres'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='meter',
            field=models.FloatField(blank=True, help_text='Meter reading', null=True),
        ),
        migrations.AlterField(
            model_name='reading',
            name='probe_dwu',
            field=models.FloatField(blank=True, help_text='PDWU is the rate of change of the water content of root zone 1, expressed in mm/day', null=True, verbose_name='Probe Daily Water Use'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='rain',
            field=models.FloatField(blank=True, help_text='Rainfall reding', null=True),
        ),
    ]
