# Generated by Django 3.0.6 on 2020-09-21 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0022_auto_20200829_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diviner',
            name='comment',
        ),
        migrations.AlterField(
            model_name='criticaldate',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='skeleton.SiteDescription'),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
