# Generated by Django 2.2.1 on 2020-01-23 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0024_auto_20200124_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherstation',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address.State'),
        ),
    ]
