# Generated by Django 3.0.6 on 2021-05-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0025_auto_20210118_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstation',
            name='average_rainfall',
            field=models.IntegerField(default=0, help_text='In mms the average 10 year rainfall for that weatherstation for a growing season (Not the full year).', null=True),
        ),
    ]
