# Generated by Django 2.2.1 on 2020-01-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0026_auto_20200130_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstation',
            name='code',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
