# Generated by Django 3.0.6 on 2021-05-24 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0027_auto_20210511_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalSoilStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(choices=[('LIG', 'Light'), ('MED', 'Medium'), ('HEV', 'Heavy')], default='HEV', max_length=3)),
                ('total_irrigation_mms', models.IntegerField(default=0, help_text='Total Irrigation for all sites of that soil type', null=True)),
                ('total_effective_irrigation', models.IntegerField(default=0, help_text='Total Effective Irrigation for all sites of that soil type', null=True)),
                ('perc_effective_irrigation', models.IntegerField(default=0, help_text='Percentage Effective Irrigation for all sites of that soil type', null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='skeleton.Season')),
            ],
            options={
                'unique_together': {('season', 'soil_type')},
            },
        ),
    ]
