# Generated by Django 2.2.1 on 2020-02-04 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0027_weatherstation_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='criticaldate',
            unique_together={('site', 'season', 'type')},
        ),
    ]
