# Generated by Django 3.0.6 on 2021-05-25 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0028_seasonalsoilstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonalsoilstat',
            name='crop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='skeleton.Crop'),
        ),
        migrations.AlterUniqueTogether(
            name='seasonalsoilstat',
            unique_together={('season', 'crop', 'soil_type')},
        ),
    ]
