# Generated by Django 2.2.1 on 2020-02-26 20:09

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skeleton', '0028_auto_20200205_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='critical_date1',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='critical_date2',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='critical_date3',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='critical_date4',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='critical_date5',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='critical_date6',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='critical_label1',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='critical_label2',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='critical_label3',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='critical_label4',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='critical_label5',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='critical_label6',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='irrigation_area',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='irrigation_crop_factor',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='irrigation_deliver_factor',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='irrigation_delivered_volume',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='irrigation_drip_days',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='irrigation_emit_space',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='irrigation_lower',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='irrigation_method',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='irrigation_plant_space',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='irrigation_position',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='irrigation_row_space',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='irrigation_time',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='irrigation_upper',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='irrigation_wet_width',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='irrigation_yield',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='season_end',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='season_start',
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('created_by', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skeleton.Variety'),
        ),
    ]
