# Generated by Django 2.2.1 on 2020-02-26 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0029_auto_20200227_0909'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crop',
            unique_together={('name', 'variety')},
        ),
    ]
