# Generated by Django 3.0.6 on 2021-06-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0029_auto_20210526_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherstation',
            name='average_rainfall',
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='code',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
    ]
