# Generated by Django 2.2.1 on 2020-03-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0030_auto_20200227_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='variety',
        ),
    ]
