# Generated by Django 3.0.6 on 2021-07-06 00:44

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skeleton', '0030_auto_20210615_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherstation',
            name='code',
            field=models.CharField(max_length=4, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='SoilProfileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#FFFFFF', max_length=7, null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('created_by', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='profile1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soil_profile_type_1', to='skeleton.SoilProfileType'),
        ),
        migrations.AddField(
            model_name='site',
            name='profile10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soil_profile_type_10', to='skeleton.SoilProfileType'),
        ),
        migrations.AddField(
            model_name='site',
            name='profile2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soil_profile_type_2', to='skeleton.SoilProfileType'),
        ),
        migrations.AddField(
            model_name='site',
            name='profile3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soil_profile_type_3', to='skeleton.SoilProfileType'),
        ),
        migrations.AddField(
            model_name='site',
            name='profile4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soil_profile_type_4', to='skeleton.SoilProfileType'),
        ),
        migrations.AddField(
            model_name='site',
            name='profile5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soil_profile_type_5', to='skeleton.SoilProfileType'),
        ),
        migrations.AddField(
            model_name='site',
            name='profile6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soil_profile_type_6', to='skeleton.SoilProfileType'),
        ),
        migrations.AddField(
            model_name='site',
            name='profile7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soil_profile_type_7', to='skeleton.SoilProfileType'),
        ),
        migrations.AddField(
            model_name='site',
            name='profile8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soil_profile_type_8', to='skeleton.SoilProfileType'),
        ),
        migrations.AddField(
            model_name='site',
            name='profile9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='soil_profile_type_9', to='skeleton.SoilProfileType'),
        ),
    ]
