# Generated by Django 3.0.6 on 2021-07-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeleton', '0031_auto_20210706_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='rooting_barrier',
            field=models.IntegerField(blank=True, choices=[(0, 0), (10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100), (110, 110), (120, 120)], default=0, help_text='Used in the Soil Profile to indicate a barrier for roots', null=True),
        ),
    ]
