# Generated by Django 2.2.1 on 2020-03-02 21:54

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skeleton', '0031_remove_site_variety'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('created_by', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(help_text='A positive or negative number indicated the amount of days away from that critical date.')),
                ('percentage', models.FloatField(help_text='A number beween 1 and 0 indicating the variation from the limit associated with the strategy.')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('created_by', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('critical_date_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skeleton.CriticalDateType')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skeleton.StrategyType')),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='lower_strategy',
            field=models.ForeignKey(blank=True, help_text='Strategy dictating deviance of Lower line for Graph', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lower_strategy_type', to='skeleton.StrategyType'),
        ),
        migrations.AddField(
            model_name='site',
            name='upper_strategy',
            field=models.ForeignKey(blank=True, help_text='Strategy dictating deviance of Upper line for Graph', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upper_strategy_type', to='skeleton.StrategyType'),
        ),
    ]
