# Generated by Django 3.0.6 on 2021-08-09 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20160213_1726'),
        ('skeleton', '0032_site_rooting_barrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='kcreading',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='address.State'),
        ),
        migrations.AddField(
            model_name='kcreading',
            name='season',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='skeleton.Season'),
        ),
        migrations.DeleteModel(
            name='VarietySeasonTemplate',
        ),
    ]
