# Generated by Django 2.2.1 on 2019-07-28 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_create_custom_vsw_view'),
    ]

    operations = [
        migrations.RunSQL(
            '''

            CREATE OR REPLACE VIEW graphs_site AS
            SELECT
                skeleton_site.id,
            	skeleton_site.name,
            	skeleton_site.variety,
            	skeleton_site.season_start,
            	skeleton_site.season_end
            FROM
            	skeleton_site;

            CREATE OR REPLACE VIEW graphs_farm AS
            SELECT
            	skeleton_farm.id,
            	skeleton_farm.name
            FROM
                skeleton_farm;

            CREATE OR REPLACE VIEW graphs_readingtype AS
            SELECT
                skeleton_readingtype.id,
            	skeleton_readingtype.name
            FROM
                skeleton_readingtype;

            CREATE OR REPLACE VIEW graphs_crop AS
            SELECT
                skeleton_crop.id,
            	skeleton_crop.name
            FROM
                skeleton_crop;
'''
        )

    ]
