# Generated by Django 2.2.1 on 2019-07-28 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_create_custom_vsw_view'),
    ]

    operations = [
        migrations.RunSQL(
            '''

            CREATE OR REPLACE VIEW graphs_site AS
            SELECT
                skeleton_site.id,
            	skeleton_site.name,
                round(skeleton_site.emitter_rate::numeric / (skeleton_site.row_spacing::numeric * skeleton_site.emitter_spacing::numeric), 2) AS application_rate
            FROM
            	skeleton_site;

            CREATE OR REPLACE VIEW graphs_farm AS
            SELECT
            	skeleton_farm.id,
            	skeleton_farm.name
            FROM
                skeleton_farm;

            CREATE OR REPLACE VIEW graphs_readingtype AS
            SELECT
                skeleton_readingtype.id,
            	skeleton_readingtype.name
            FROM
                skeleton_readingtype;

            CREATE OR REPLACE VIEW graphs_product AS
            SELECT
                skeleton_product.id,
            	skeleton_crop.name AS crop,
                skeleton_variety.name AS variety
            FROM
                skeleton_product
            LEFT JOIN skeleton_crop ON skeleton_crop.id = skeleton_product.crop_id
            LEFT JOIN skeleton_variety ON skeleton_variety.id = skeleton_product.variety_id;
'''
        )

    ]
