# Generated by Django 2.2.3 on 2019-08-16 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graphs', '0002_create_custom_info_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'graphs_farm',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReadingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'graphs_readingtype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
                ('season_start', models.DateField()),
                ('season_end', models.DateField()),
            ],
            options={
                'db_table': 'graphs_site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='vsw_reading',
            fields=[
                ('date', models.DateField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='graphs.Site')),
                ('depth1', models.IntegerField()),
                ('count1', models.FloatField()),
                ('vsw1', models.FloatField()),
                ('depth2', models.IntegerField()),
                ('count2', models.FloatField()),
                ('vsw2', models.FloatField()),
                ('depth3', models.IntegerField()),
                ('count3', models.FloatField()),
                ('vsw3', models.FloatField()),
                ('depth4', models.IntegerField()),
                ('count4', models.FloatField()),
                ('vsw4', models.FloatField()),
                ('depth5', models.IntegerField()),
                ('count5', models.FloatField()),
                ('vsw5', models.FloatField()),
                ('depth6', models.IntegerField()),
                ('count6', models.FloatField()),
                ('vsw6', models.FloatField()),
                ('depth7', models.IntegerField()),
                ('count7', models.FloatField()),
                ('vsw7', models.FloatField()),
                ('depth8', models.IntegerField()),
                ('count8', models.FloatField()),
                ('vsw8', models.FloatField()),
                ('depth9', models.IntegerField()),
                ('count9', models.FloatField()),
                ('vsw9', models.FloatField()),
            ],
            options={
                'db_table': 'graphs_vsw',
                'managed': False,
            },
        ),
    ]
