# Generated by Django 2.2.3 on 2020-03-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0003_farm_readingtype_site_vsw_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='vsw_strategy',
            fields=[
                ('strategytype_id', models.IntegerField()),
                ('strategy_name', models.TextField()),
                ('site_name', models.TextField()),
                ('reading_type_name', models.IntegerField()),
                ('reading_date', models.DateField(null=True)),
                ('rz1', models.FloatField()),
                ('strategy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('days', models.FloatField()),
                ('percentage', models.FloatField()),
                ('critical_date_type', models.FloatField()),
                ('critical_date', models.DateField(null=True)),
                ('strategy_date', models.DateField(null=True)),
                ('upper_strategy_vsw', models.FloatField()),
                ('lower_strategy_vsw', models.FloatField()),
            ],
            options={
                'db_table': 'graphs_strategy',
                'managed': False,
            },
        ),
    ]
