# Generated by Django 2.2.1 on 2020-03-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0004_vsw_strategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('variety', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'graphs_product',
                'managed': False,
            },
        ),
    ]
