# Generated by Django 3.0.6 on 2021-07-06 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0004_auto_20200922_1146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site',
        ),
    ]
