# Generated by Django 3.0.6 on 2021-07-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0005_delete_site'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farm',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ReadingType',
        ),
        migrations.AlterModelOptions(
            name='vsw_reading',
            options={'get_latest_by': 'date', 'managed': False, 'ordering': ('-date', 'type')},
        ),
    ]
